import WorkflowItem from "../workflowItem";
import { useLocale } from "../../../hooks";
import cn from "clsx";
interface Props {}

const Workflow = (props: Props) => {
  const isEn = useLocale();
  return (
    <div className="mt-20">
      <WorkflowItem
        year={2016}
        title={isEn ? "research idea emereged" : "研究概念產生"}
        content={
          isEn
            ? "[It generated the first GRF proposal in 2016]"
            : "[2016年製成第一份GRF計劃書]"
        }
        outsideLink="https://cerg1.ugc.edu.hk/cergprod/scrrm00542.jsp?proj_id=12606618&old_proj_id=22606618&proj_title=&isname=koon&ioname=&institution=HKBU&subject=&pages=1&year=&theSubmit=12606618"
      />
      <WorkflowItem
        year={2017}
        title={isEn ? `"picturing hongkong" exhibition` : `《圖繪香港展覽》`}
        content={
          isEn ? "[inspired by this research idea]" : "[展覽轉化自此研究概念]"
        }
        outsideLink="https://library.hkust.edu.hk/exhibitions/chinese-ink/?lang=cht"
      />
      <WorkflowItem
        year={2018}
        title={isEn ? `research on hongkong langscapes` : `香港風景研究`}
        content={
          isEn
            ? "[IT TURNED INTO A NUMBER OF ARCHIVES]"
            : "[研究轉化成數個檔案]"
        }
        src="archives"
        contentClassName={cn("text-xlg", { ["text-lg"]: !isEn })}
      />
      <WorkflowItem
        year={2020}
        title={isEn ? `"hongkong impression" exhibition` : `《香港印象》展覽`}
        content={
          isEn
            ? "[It was generated by parts of the research materials]"
            : "[展覽轉化自此研究的部分資料]"
        }
        outsideLink="http://www.artmuseum.cuhk.edu.hk/zh/exhibition/current/detail/52"
      />
      <WorkflowItem
        year={2021}
        title={
          isEn ? `art productions of "here & there"` : `《極目足下》藝術創作`
        }
        content={isEn ? "6 LOCATIONS / 6 ARITST" : "[六處地方 / 六位藝術家]"}
        src="six"
        contentClassName={cn("text-xlg", { ["text-lg"]: !isEn })}
      />
      <WorkflowItem
        last
        year={2021}
        title={isEn ? `"here & there" exhibition` : `《極目足下》展覽`}
        src="exhibition"
      />
    </div>
  );
};

export default Workflow;
