import WorkflowItem from "../workflowItem";
import { useLocale } from "../../../hooks";
interface Props {}

const Workflow = (props: Props) => {
  const isEn = useLocale();
  return (
    <div className="mt-20">
      <WorkflowItem
        year={2016}
        title={isEn ? "research idea emereged" : "研究概念產生"}
        content={
          isEn
            ? "[the first GRF proposal generated in 2016]"
            : "2016年製成第一分GRF計畫書"
        }
      />
      <WorkflowItem
        year={2017}
        title={isEn ? `"picturing hongkong" exhibition` : `《圖繪香港展覽》`}
        content={isEn ? "[inspired by this research idea]" : "轉化自此研究概念"}
        outsideLink="https://library.hkust.edu.hk/exhibitions/chinese-ink/?lang=cht"
      />
      <WorkflowItem
        year={2018}
        title={isEn ? `research on hongkong langscapes` : `香港風景研究`}
        content={isEn ? "ARCHIVES" : "檔案"}
        src="archives"
      />
      <WorkflowItem
        year={2020}
        title={isEn ? `"hongkong impression" exhibition` : `《香港印象》展覽`}
        content={
          isEn
            ? "[generated by part of this research materials]"
            : "[轉化自此研究的部分資料]"
        }
        outsideLink="http://www.artmuseum.cuhk.edu.hk/zh/exhibition/current/detail/52"
      />
      <WorkflowItem
        year={2021}
        title={
          isEn ? `art productions of "here & there"` : `《極目足下》藝術創作`
        }
        content={isEn ? "6 LOCATIONS / 6 ARITST" : "六處地方 / 六位藝術家"}
        src="six"
      />
      <WorkflowItem
        last
        year={2021}
        title={isEn ? `"here & there" exhibition` : `《極目足下》展覽`}
        src="exhibition"
      />
    </div>
  );
};

export default Workflow;
